import theme from '@/config/themeColor';
import TanstackQueryProvider from '@/shared/provider/TanstackQueryProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import './globals.scss';

const inter = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${montserrat.variable}`}>
      <body>
        <ConfigProvider theme={theme}>
          <AntdRegistry>
            <TanstackQueryProvider>{children}</TanstackQueryProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
